# io config
input_pcd_path: "data/longhua_building_segment.xyz"
inst_scalar: true
output_inst_color: true

save_path: "longhua_inst_convexhull"
obj_save_path: "longhua_inst_convexhull.obj"
footprint_save_path: ""
ground_segment_pcd_save_path: 'ground_segment.xyz'
building_segment_pcd_save_path: 'building_segment.xyz'
color_file_path: 'color.txt'

boundary_mode: "alpha-shape"
output_boundary_path: "longhua_inst_boundary.txt"

# dbscan
need_cluster: true
segment_z : 96
dbscan_eps: 6
dbscan_min_points: 15

# layer config
layer_num: 30
layer_mode: "convex-hull"
area_threshold: 1.05
ground_z:  80




